config/routes.rb
Menu::Application.routes.draw do
  
  constraints :host => /^#{APP_CONFIG[:domain]}$/ do
    defaults :host => APP_CONFIG[:domain] do
      post "/" => "restaurants#create", :as => :restaurants
      get "/" => "restaurants#new", :as => :restaurants
    end
  end
  
  resources :items, :except => [:new] do
    member do
      put :expire
      put :renew
      put :up
      put :down  
    end
  end
  delete 'items' => 'items#destroy_all'
  
  get 'settings' => 'restaurants#edit', :as => :settings
  put 'settings' => 'restaurants#update', :as => :restaurant
  
  delete 'logout' => 'sessions#destroy', :as => :logout
  get  'login' => 'sessions#new', :as => :login
  post 'login' => 'sessions#create', :as => :login
  root :to => "items#index"

  

  
  

  

end

app/models/item.rb
# coding: utf-8
class Item < ActiveRecord::Base
  belongs_to :restaurant
  acts_as_list :scope => :restaurant
  
  default_scope order('position')
  scope :active, where("active = ?", true)
  scope :fresh, where("updated_at > ?", 1.day.ago)
  
  validates_presence_of :name, :price, :restaurant_id
  validates_associated :restaurant, :on => :create
  validates_numericality_of :price, :greater_than => 0
  
  
  def price= raw_value
    match = raw_value.to_s.match(/-?\d+([.,]\d+)?/)
    return raw_value unless match
    corrected_value = match.to_s.sub(',','.').to_d
    write_attribute :price, corrected_value
  end
  
  def name= raw_name
    return if raw_name.blank?
    write_attribute :name, titleize_tr(raw_name)
  end
  def details= raw_details
    return if raw_details.blank?
    write_attribute :details, titleize_tr(raw_details)
  end
  
  private
  
  def titleize_tr string
    up="ABCÇDEFGĞHIİJLKMNOÖPQRSŞTUÜVWXYZ"
    dn="abcçdefgğhıijlkmnoöpqrsştuüvwxyz"
    string.gsub(/[ABCÇDEFGĞHIİJLKMNOÖPQRSŞTUÜVWXYZ]+/) { |w| w[0] + w[1..-1].tr(up, dn)}
  end
end

app/models/restaurant.rb
# coding: utf-8
require 'heroku'

class Restaurant < ActiveRecord::Base
  # new columns need to be added here to be writable through mass assignment
  attr_accessible :domain, :email, :password, :password_confirmation, :name, :info
  attr_readonly :domain
  
  attr_accessor :password
  before_save :prepare_password
  
  if Rails.env.production?
    before_create :register_domain
    before_destroy :unregister_domain
  end
  
  validates_presence_of :domain, :name
  validates_uniqueness_of :domain
  validates_format_of :domain, :with => /^[a-z][a-z0-9-]+(\.[a-z][a-z0-9-]+)+$/i
  validates_exclusion_of :domain, :in => APP_CONFIG[:reserved_domains]
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password
  validates_length_of :password, :minimum => 4, :allow_blank => true
  
  has_many :items, :dependent => :destroy
  
  def matching_password?(pass)
    self.password_hash == encrypt_password(pass)
  end
  
  private
  
  def prepare_password
    unless password.blank?
      self.password_salt = Digest::SHA1.hexdigest([Time.now, rand].join)
      self.password_hash = encrypt_password(password)
    end
  end
  
  def encrypt_password(pass)
    Digest::SHA1.hexdigest([pass, password_salt].join)
  end
  
  def register_domain
    Heroku::Client.new(ENV['HEROKU_USER'], ENV['HEROKU_PASSWORD']).add_domain('menu', domain)
  rescue RestClient::RequestFailed
    errors.add :domain, :not_yet_routed
    false
  end
  def unregister_domain
    Heroku::Client.new(ENV['HEROKU_USER'], ENV['HEROKU_PASSWORD']).remove_domain('menu', domain)
  end
  
end

app/controllers/application_controller.rb
# coding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :admin?
  
  private
  
  def admin?
    @restaurant and session[:restaurant_id] == @restaurant.id
  end
  
  def check_for_admin
    unless admin?
      redirect_to root_url, :alert => t("errors.app.denied")
    end
  end
  
  def set_restaurant
    @restaurant = Restaurant.find_by_domain(request.host)
    
    unless @restaurant
      flash[:restaurant] = Restaurant.new({:domain => request.host})
      redirect_to restaurants_url(:port => request.port), :alert => t("errors.app.no_restaurant")
    end
  end
  
end

app/controllers/items_controller.rb
# coding: utf-8
class ItemsController < ApplicationController
  before_filter :set_restaurant
  before_filter :check_for_admin, :except => :index
  
  def index
    @date = Date.today

    @items = @restaurant.items.all
    
    if admin?
      @form_item = flash[:item] || @restaurant.items.build
    end
  end
  
  def edit
    flash[:item] = Item.find(params[:id])
    redirect_to root_url
  end

  def create
    @item = @restaurant.items.build(params[:item])
    
    if @item.valid?
      @item.save!
      notice = t(:'notice.item.created', :name => @item.name)
      redirect_to root_url
    else
      alert = t(:'errors.models.created', :name => t(:'activerecord.models.item'))
      flash[:item] = @item
      redirect_to root_url(:anchor => "errorExplanation")
    end
  end
  
  def update
    updater do
      @item.update_attributes params[:item]
    end
  end
  
  
  def destroy
    @item = Item.find(params[:id])
    
    if @item.destroy
      flash.notice = t(:'notice.item.deleted', :name => @item.name)
      redirect_to root_url 
    else
      flash.alert = t(:'errors.models.deleted', :name => @item.name)
      redirect_to root_url
    end
  end
  
  def destroy_all
    if @restaurant.items.destroy_all.length > 0
      flash.notice = t(:'notice.item.deleted_all')
    else
      flash.alert = t(:'errors.models.deleted_all')
    end
    redirect_to root_url
  end
      
  def expire
    updater do
      @item.active = false
    end
  end
  
  def renew
    updater do
      @item.active = true
    end
  end
  
  def up
    updater do
      @item.move_higher
    end
  end
  
  def down
    updater do
      @item.move_lower
    end
  end
  
  private
  
  def updater
    @item = @restaurant.items.find(params[:id])
    
    yield
    
    if @item.valid?
      @item.save!
      flash.notice = t(:'notice.item.updated', :name => @item.name)
      redirect_to root_url
    else
      flash.alert = t(:'errors.models.updated', :name => @item.name)
      flash[:item] = @item
      redirect_to root_url(:anchor => "errorExplanation")
    end
  end
  
end

app/controllers/restaurants_controller.rb
# coding: utf-8
class RestaurantsController < ApplicationController
  before_filter :set_restaurant, :check_for_admin, :only => [:edit, :update]
  
  def new
    @restaurant = flash[:restaurant] || Restaurant.new
  end
  
  def create
    @restaurant = Restaurant.new(params[:restaurant])
    if @restaurant.save
      session[:restaurant_id] = @restaurant.id
      redirect_to root_url(:host => @restaurant.domain, :port => request.port), :notice => t('notice.restaurant.created')
    else
      render :action => 'new'
    end
  end
  
  def edit
  end
  
  def update
    @restaurant.update_attributes(params[:restaurant])
    if @restaurant.save
      redirect_to root_url, :notice => t('notice.restaurant.updated')
    else
      render 'edit'
    end
  end
end

app/controllers/sessions_controller.rb
# coding: utf-8
class SessionsController < ApplicationController
  before_filter :set_restaurant
  
  def new
  end
  
  def create
    if @restaurant.matching_password? params[:password]
      session[:restaurant_id] = @restaurant.id
      redirect_to root_url, :notice => t('notice.session.created')
    else
      redirect_to login_url, :alert => t('errors.session.wrong_password')
    end
  end
  
  def destroy
    session[:restaurant_id] = nil
    redirect_to root_url, :notice => t('notice.session.deleted')
  end
end

app/helpers/application_helper.rb
# coding: utf-8
module ApplicationHelper
  def flash_paragraphs
    output = ""
    [:notice, :alert].each do |f|
      if flash[f] then
        output << content_tag(:p, :class => f.to_s) do
          flash[f]
        end
      end
    end
    raw output
  end
end

app/helpers/items_helper.rb
# coding: utf-8
module ItemsHelper
  def small_cents(p)
    raw p.sub(/([.,]\d+\s)/, content_tag(:small, '\1'))
  end
end

app/helpers/restaurants_helper.rb
# coding: utf-8
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
# coding: utf-8
module SessionsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for(item) do |f| %>
  <h1><%= item.name.presence || t(:new_item) %></h1>
  <%= f.error_messages %>
  <%= f.association :restaurant, :as => :hidden %>
  <dl>
    <%= f.input :name, :wrapper_tag => :dt, :placeholder => 'Leziz yemek' %>
    <%= f.input :details %>
    <%= f.input :price, :as => :string %>
    <%= f.input :active %>
    <%= f.label :required_info %>
    <%= f.button :submit %>
  </dl>
<% end %>

app/views/items/_item.atom.erb
<%= content_tag_for :p, item, :class => (item.active? ? "" : "inactive") do -%>
  <strong><%= item.name %></strong> 
  <%= content_tag :span, item.details unless item.details.blank? %> 
  — <em><%= number_to_currency(item.price) %></em>
  
<%- end -%>

app/views/items/_item.html.erb
<%= content_tag_for :dl, item, :class => (item.active? ? "" : "inactive") do -%>
  <dt><%= item.name %></dt>
  <%= content_tag :dd, item.details unless item.details.blank? %>
  <dd><%= small_cents number_to_currency(item.price) %></dd>
  <%- if admin? -%>
  <div class="admin">
<%= link_to t(:'admin.button.expire'), expire_item_path(item), :method => :put if item.active? -%>
<%= link_to t(:'admin.button.renew'), renew_item_path(item), :method => :put unless item.active? -%>
<%= link_to t(:'admin.button.edit'), edit_item_path(item), :rel => 'nofollow' -%>
<%= link_to t(:'admin.button.delete'), item, :method => :delete -%>
<%= link_to(t(:'admin.button.up'), up_item_path(item), :method => :put ) unless item.first? -%>
<%= link_to(t(:'admin.button.down'), down_item_path(item), :method => :put ) unless item.last? %>
  </div>
  <%- end -%>
<%- end -%>

app/views/items/_login.html.erb
<%= form_tag login_path, :method => :post do %>
  <h1><%= t :admin_login %></h1>
  <%= label_tag :password, t('helpers.label.password')%>
  <%= password_field_tag :password %>
  <%= submit_tag t('helpers.submit.login') %>
<% end -%>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.atom.erb
<?xml version="1.0" encoding="UTF-8"?>
<feed xml:lang="tr-TR" xmlns="http://www.w3.org/2005/Atom">
  <id>tag:<%= @restaurant.domain %></id>
  <link type="text/html" href="http://<%= @restaurant.domain %>" rel="alternate"/>
  <title><%= @restaurant.name %></title>
  <entry>
    <id><%= @date %></id>
    <title><%= l @date, :format => :close %></title>
    <content type="html">
      <%= render @items %>
    </content>
  </entry>
</feed>

app/views/items/index.html.erb
<address><%= @restaurant.info %></address>

<date><%= l @date, :format => :close %></date>

<%= render "layouts/notice" if admin? %>

<%= flash_paragraphs %>


<div id="menu">
	<% @items.each do |item| %>
		<% if admin? && (item == @form_item) %>
		  <% @form_rendered = true %>
		  <%= render "form", :item => @form_item %>
		  <p class="admin"><%= link_to t(:'admin.button.cancel_edit'), root_path %></p>
		<% else %>
		  <%= render item %>
		<% end -%>
	<% end -%>
	<%= render "form", :item => @form_item if admin? unless @form_rendered %>
</div>



<p class='admin'>
    <% if admin? %>
      <%= link_to t(:'admin.button.delete_all'), items_path, :method => :delete, :confirm => t(:'admin.confirm.delete_all') -%>
      <%= link_to t(:'admin.button.settings'), settings_path %>
      <%= link_to t(:'admin.button.logout'), logout_path, :method => :delete %>
    <% else %>
      <%= link_to t(:'admin.button.login'), login_path %>
    <% end -%>
</p>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Details:</b>
  <%= @item.details %>
</p>

<p>
  <b>Price:</b>
  <%= @item.price %>
</p>

<p>
  <b>Position:</b>
  <%= @item.position %>
</p>

<p>
  <b>Active:</b>
  <%= @item.active %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/_ie.html.erb
<meta http-equiv="X-UA-Compatible" content="chrome=1">
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<link rel="stylesheet" href="/stylesheets/ie.css" type="text/css" charset="utf-8">

app/views/layouts/_notice.tr.html.erb
<div class="side">
		Lütfen  sisteme dair görüş, eleştiri ve önerilerinizi
		<a href="mailto:oneri@menu.gen.tr">oneri@menu.gen.tr</a>
		adresine iletin.
</div>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <title><%= @restaurant.name %> — <%= t :todays_menu %></title>
	<%= stylesheet_link_tag 'menu' %>
	<!--[if lt IE 9]><%= render :partial => 'layouts/ie' %><![endif]-->
	<%= javascript_include_tag :defaults %>
	<%= csrf_meta_tag %>
	<%= auto_discovery_link_tag(:atom, {:action => "index", :format => "atom"},
    {:title => "Feed"}) if controller.is_a? ItemsController %>
  </head>
  <body>
    <h3><%= t(:todays_menu) %></h3>
    <h1 id="title"><%= @restaurant.name %></h1>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
<h1><%= t( @restaurant.new_record? ? :new_restaurant : :settings ) %></h1>
<dl>
  <%= f.error_messages %>
  <%= f.input :name %>
  <%= f.input :domain if @restaurant.new_record? %>
  <%= f.input :info %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.label :required_info %>
  <%= f.button :submit %>
</dl>
<% end %>

app/views/restaurants/_welcome.tr.html.erb
<h1>Kendi menünüzü oluşturun</h1>

<div class='side'>
  <strong>Günün Menüsü</strong>'ne hoşgeldiniz. Günün menüsü, restoranların günlük menülerini internet üzerinden 
  pratik bir şekilde yayınlayabilmeleri için bir sistem. Siz de bir restoran sahibi iseniz Günün Menüsü'ne üye olun,
  ister <strong>menu.gen.tr</strong> alan adı altında (örn: <strong>bizimrestoran</strong>.menu.gen.tr) ister kendi alan adınız altında 
  (örn: <strong>bizimrestoran.com.tr</strong>) yayınlayın. Günün Menüsü, şimdilik geliştirme sürecinde ve geliştirme süreci bitene 
  kadar tamamen bedava.
</div>

app/views/restaurants/edit.html.erb
<%= flash_paragraphs %>

<%= render 'form' %>

<p class='admin'>
  <%= link_to t(:'admin.button.cancel_settings'), root_path %>
</p>

app/views/restaurants/new.html.erb
<%= render 'welcome' %>

<%= flash_paragraphs %>

<%= render 'form' %>